name: Decompile AppleScript

on:
  workflow_dispatch:

jobs:
  decompile:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show file info
        run: |
          ls -l
          file 1.scpt

      - name: Decompile scpt
        run: |
          osadecompile 1.scpt
